# Generated by Django 5.2.4 on 2025-07-13 07:13

import api.utils.Fields
import charidfield.fields
import cuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='cur_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=5)),
                ('iso_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='consumer',
            name='stripe_customer_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='prc_', primary_key=True, serialize=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('frequency', api.utils.Fields.EnumField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default=None, null=True)),
                ('apple_id', models.CharField(max_length=255, null=True)),
                ('google_id', models.CharField(max_length=255, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='pay_', primary_key=True, serialize=False, unique=True)),
                ('apple_receipt_id', models.TextField(null=True)),
                ('apple_receipt_id_hash', models.CharField(db_index=True, null=True, unique=True)),
                ('google_receipt_id', models.TextField(null=True)),
                ('google_receipt_id_hash', models.CharField(db_index=True, null=True, unique=True)),
                ('stripe_receipt_id', models.CharField(db_index=True, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(db_index=True, null=True, unique=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.consumer')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='pkg_', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='api.price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to='api.consumer')),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('unsubscribed_at', models.DateTimeField(null=True)),
                ('subscribed_at', models.DateTimeField(null=True)),
                ('last_checked_at', models.DateTimeField(null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.package')),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
