# Generated by Django 5.2.4 on 2025-07-19 05:09

import api.utils.Fields
import charidfield.fields
import cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_attribute_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='pst_', primary_key=True, serialize=False, unique=True)),
                ('status', api.utils.Fields.EnumField(choices=[('draft', 'draft'), ('archived', 'archived'), ('prompted', 'prompted'), ('rejected', 'rejected'), ('published', 'published')], default='draft')),
                ('type', api.utils.Fields.EnumField(choices=[('video', 'video'), ('podcast', 'podcast'), ('article', 'article')], default='video')),
                ('published_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('body', models.TextField(null=True)),
                ('views_no', models.PositiveIntegerField(default=0)),
                ('impressions_no', models.PositiveIntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts_as_banner', to='api.image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.file')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts_as_thumbnail', to='api.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='evt_', primary_key=True, serialize=False, unique=True)),
                ('type', api.utils.Fields.EnumField(choices=[('view', 'view'), ('impression', 'impression')], default='view')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.consumer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
