# Generated by Django 5.2.4 on 2025-07-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_consumer_date_of_birth_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
