# Generated by Django 5.2.4 on 2025-08-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_participant_message_session_participant_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='usage',
            field=models.JSONField(null=True),
        ),
    ]
