# Generated by Django 5.2.4 on 2025-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.CharField(default='gemini-2.5-flash', max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='observations',
            field=models.TextField(null=True),
        ),
    ]
