# Generated by Django 5.2.4 on 2025-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message_reasoning_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='counter_emotions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='flexible_thinking',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='next_steps',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='staying_present',
            field=models.TextField(null=True),
        ),
    ]
