# Generated by Django 5.2.4 on 2025-09-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_exercise_message_completion_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='counter_emotions',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='flexible_thinking',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='staying_present',
        ),
    ]
