# Generated by Django 5.2.4 on 2025-09-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_tag_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.asset'),
        ),
    ]
