# Generated by Django 5.2.4 on 2025-09-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_message_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='tags',
            field=models.ManyToManyField(related_name='steps', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(related_name='assets', to='api.tag'),
        ),
    ]
