# Generated by Django 5.2.4 on 2025-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_step_tags_alter_asset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='icon_svg',
            field=models.TextField(null=True),
        ),
    ]
