# Generated by Django 5.2.4 on 2025-09-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_asset_tags_alter_step_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstep',
            name='last_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_last_asset', to='api.asset'),
        ),
    ]
