# Generated by Django 5.2.4 on 2025-09-26 07:43

import api.utils.Fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_sessionstep_last_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.session'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=api.utils.Fields.EnumField(choices=[('text', 'text'), ('date', 'date'), ('number', 'number'), ('boolean', 'boolean'), ('single_choice', 'single_choice'), ('multiple_choice', 'multiple_choice')], default='text'),
        ),
    ]
