# Generated by Django 5.2.4 on 2025-09-26 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_question_session_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_as_last_asset', to='api.asset'),
        ),
    ]
