# Generated by Django 5.2.4 on 2025-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_sessionstep_completion_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='key',
            field=models.CharField(null=True),
        ),
    ]
