# Generated by Django 5.2.4 on 2025-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_exercise_options_exercise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='block_on_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='blocks_exercise',
            field=models.BooleanField(default=False),
        ),
    ]
