# Generated by Django 5.2.4 on 2025-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='average_duration',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='step',
            name='average_duration',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='step',
            name='success_title',
            field=models.CharField(default='Well Done!', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='complete_on_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]