# Generated by Django 5.2.4 on 2025-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complete_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
