# Generated by Django 5.2.4 on 2025-12-15 05:32

import api.utils.Fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_role_permissions_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='status',
            field=api.utils.Fields.EnumField(choices=[('draft', 'draft'), ('archived', 'archived'), ('published', 'published')], default='draft'),
        ),
    ]
