# Generated by Django 5.2.4 on 2026-02-12 03:48

import api.utils.Fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='usage',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=api.utils.Fields.EnumField(choices=[('draft', 'draft'), ('archived', 'archived'), ('prompted', 'prompted'), ('rejected', 'rejected'), ('published', 'published'), ('generating', 'generating')], default='draft'),
        ),
    ]
