# Generated by Django 5.2.16 on 2026-07-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_session_usage_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='step',
            name='completion_label',
            field=models.CharField(max_length=255),
        ),
    ]
