# Generated by Django 5.2.16 on 2026-08-01 18:24

import api.utils.Fields
import charidfield.fields
import cuid
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_knowledge_permissions(apps, schema_editor):
    Permissions = apps.get_model("api", "Permissions")
    Role = apps.get_model("api", "Role")

    defaults_by_name = {
        "Super Admin": ["view", "create", "edit", "delete"],
        "Admin": ["view", "create", "edit"],
        "Read Only": ["view"],
    }

    for role in Role.objects.all():
        try:
            perms = Permissions.objects.get(role_id=role.id)
        except Permissions.DoesNotExist:
            continue

        if role.name in defaults_by_name:
            perms.knowledge = defaults_by_name[role.name]
        elif not perms.knowledge:
            perms.knowledge = ["view"]
        perms.save(update_fields=["knowledge"])


def unseed_knowledge_permissions(apps, schema_editor):
    Permissions = apps.get_model("api", "Permissions")
    Permissions.objects.all().update(knowledge=[])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_aiprovider_aiproviderauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeField',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='knf_', primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('value_type', api.utils.Fields.EnumField(choices=[('text', 'text'), ('number', 'number'), ('boolean', 'boolean'), ('single_choice', 'single_choice'), ('multiple_choice', 'multiple_choice')], default='text')),
                ('sensitive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='permissions',
            name='knowledge',
            field=django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete')], default='view'), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='KnowledgeQuestion',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='knq_', primary_key=True, serialize=False, unique=True)),
                ('prompt', models.TextField()),
                ('trigger', api.utils.Fields.EnumField(choices=[('first_session', 'first_session'), ('after_n_sessions', 'after_n_sessions'), ('on_exercise_completion', 'on_exercise_completion'), ('manual_only', 'manual_only')], default='manual_only')),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('suggested_responses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('extraction_prompt', models.TextField(blank=True, default='')),
                ('flows', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('initial', 'initial'), ('return', 'return'), ('refresh', 'refresh')], default='initial'), blank=True, default=list, size=None)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.knowledgefield')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='kne_', primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('source', api.utils.Fields.EnumField(choices=[('onboarding', 'onboarding'), ('question', 'question'), ('ai', 'ai'), ('admin', 'admin')], default='onboarding')),
                ('confidence', models.FloatField(default=1.0)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='api.attribute')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='api.consumer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to='api.session')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.knowledgefield')),
                ('knowledge_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='api.knowledgequestion')),
            ],
            options={
                'indexes': [models.Index(fields=['consumer', 'field', '-created_at'], name='api_knowled_consume_278e16_idx'), models.Index(fields=['consumer', '-created_at'], name='api_knowled_consume_7a0b36_idx'), models.Index(fields=['source'], name='api_knowled_source_90f0f3_idx')],
            },
        ),
        migrations.RunPython(seed_knowledge_permissions, unseed_knowledge_permissions),
    ]
