# Generated by Django 5.2.16 on 2026-08-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_exercise_category'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moodentry',
            new_name='api_moodent_consume_5ca28a_idx',
            old_name='api_moodent_consume_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userobservation',
            new_name='api_userobs_consume_8d3608_idx',
            old_name='api_userobs_consume_gen_idx',
        ),
    ]
