# Generated by Django 5.2.16 on 2026-08-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_rename_index_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="abandoned",
            field=models.BooleanField(default=False),
        ),
    ]
