# Generated by Django 5.2.16 on 2026-09-14 07:59

import charidfield.fields
import cuid
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_voice_grant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaleSubmission",
            fields=[
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "id",
                    charidfield.fields.CharIDField(
                        default=cuid.cuid,
                        help_text="cuid-format identifier for this entity.",
                        max_length=40,
                        prefix="ssub_",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "scale_type",
                    models.CharField(
                        choices=[
                            ("anxiety", "Anxiety"),
                            ("positive_emotion", "Positive Emotion"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "total_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("submitted_on", models.DateField()),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale_submissions",
                        to="api.consumer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="scalesubmission",
            index=models.Index(
                fields=["consumer", "submitted_on"],
                name="api_ssub_consumer_on_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="scalesubmission",
            constraint=models.UniqueConstraint(
                fields=("consumer", "scale_type", "submitted_on"),
                name="uniq_scale_submission_per_day",
            ),
        ),
    ]
