# Generated by Django 5.2.16 on 2026-09-23 14:29

import api.utils.Fields
import charidfield.fields
import cuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _slug(value, fallback):
    from django.utils.text import slugify

    text = slugify(value or "")[:200]
    return text or fallback


def backfill_check_in(apps, schema_editor):
    Exercise = apps.get_model("api", "Exercise")
    Exercise.objects.update(
        check_in_enabled=models.F("pre_exercise_enabled"),
        check_in_tone=models.F("pre_exercise_description"),
        check_in_instruction=models.F("pre_exercise_instruction"),
        check_in_goal=models.F("pre_exercise_goal"),
        check_in_summary_prompt=models.F("pre_exercise_completion_prompt"),
        check_in_start_button_label=models.F("pre_exercise_start_button_label"),
    )


def backfill_steps(apps, schema_editor):
    Step = apps.get_model("api", "Step")
    seen = set()
    updates = []
    steps = Step.objects.all().order_by("exercise_id", "order", "id")
    for step in steps:
        base = _slug(step.title, "step")
        key = base
        suffix = 2
        while (step.exercise_id, key) in seen:
            key = f"{base}-{suffix}"
            suffix += 1
            if len(key) > 255:
                key = key[:255]
        seen.add((step.exercise_id, key))
        step.key = key
        step.done_when = step.completion_criteria
        updates.append(step)
    if updates:
        Step.objects.bulk_update(updates, ["key", "done_when"], batch_size=500)


def backfill_question_keys(apps, schema_editor):
    Question = apps.get_model("api", "Question")
    updates = []
    for question in Question.objects.all().iterator(chunk_size=500):
        question.key = _slug(question.title, "question")
        updates.append(question)
        if len(updates) >= 500:
            Question.objects.bulk_update(updates, ["key"])
            updates = []
    if updates:
        Question.objects.bulk_update(updates, ["key"])


def backfill_session_state(apps, schema_editor):
    Session = apps.get_model("api", "Session")
    Session.objects.filter(completed_at__isnull=False).update(state="completed")
    Session.objects.filter(
        completed_at__isnull=True,
        exercise_id__isnull=True,
    ).update(state="general")
    Session.objects.filter(
        completed_at__isnull=True,
        exercise_id__isnull=False,
    ).update(state="step_active")


def seed_prompt_versions(apps, schema_editor):
    from api.utils import Constants

    Setting = apps.get_model("api", "Setting")
    PromptVersion = apps.get_model("api", "PromptVersion")
    seeds = [
        (
            Constants.PROMPT_KEY_THERAPEUTIC,
            "therapeutic_prompt",
            Constants.PROMPT_THERAPEUTIC_INSTRUCTIONS,
        ),
        (
            Constants.PROMPT_KEY_GOALS,
            "general_prompt",
            Constants.PROMPT_GENERAL_GOALS,
        ),
        (
            Constants.PROMPT_KEY_OBSERVATIONS_INSTRUCTION,
            Constants.SETTING_KEY_OBSERVATIONS_INSTRUCTION,
            Constants.DEFAULT_OBSERVATIONS_INSTRUCTION,
        ),
        (
            Constants.PROMPT_KEY_OBSERVATIONS_TONE_GUIDE,
            Constants.SETTING_KEY_OBSERVATIONS_TONE_GUIDE,
            Constants.DEFAULT_OBSERVATIONS_TONE_GUIDE,
        ),
    ]
    for key, setting_key, default in seeds:
        if PromptVersion.objects.filter(key=key, version=1).exists():
            continue
        setting = Setting.objects.filter(
            key=setting_key,
            deleted_at__isnull=True,
        ).first()
        body = default
        if setting is not None and setting.value:
            body = setting.value
        PromptVersion.objects.create(
            key=key,
            body=body,
            version=1,
            active=True,
        )


def backfill_wp1(apps, schema_editor):
    backfill_check_in(apps, schema_editor)
    backfill_steps(apps, schema_editor)
    backfill_question_keys(apps, schema_editor)
    backfill_session_state(apps, schema_editor)
    seed_prompt_versions(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_user_settings_voice_id_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalCase',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='evlc_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', api.utils.Fields.EnumField(choices=[('triage', 'triage'), ('exercise', 'exercise'), ('risk', 'risk'), ('sensitive', 'sensitive'), ('failover', 'failover'), ('depth', 'depth')], default='triage')),
                ('transcript', models.JSONField(blank=True, null=True)),
                ('expected', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='evrn_', primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_versions', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='prmv_', primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('version', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionMetric',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='smet_', primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source', api.utils.Fields.EnumField(choices=[('form', 'form'), ('knowledge', 'knowledge')], default='form')),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='check_in_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='check_in_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='check_in_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='check_in_start_button_label',
            field=models.CharField(blank=True, default='Start exercise', max_length=24),
        ),
        migrations.AddField(
            model_name='exercise',
            name='check_in_summary_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='check_in_tone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='depth_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='framework_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reference_material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sensitive_fields_allowed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='use_when',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='review_status',
            field=api.utils.Fields.EnumField(choices=[('accepted', 'accepted'), ('pending_review', 'pending_review'), ('rejected', 'rejected')], default='accepted'),
        ),
        migrations.AddField(
            model_name='knowledgequestion',
            name='follow_up_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgequestion',
            name='generic_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='message',
            name='probe_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='question_kind',
            field=api.utils.Fields.EnumField(choices=[('none', 'none'), ('open', 'open'), ('closed', 'closed'), ('readiness', 'readiness')], default='none'),
        ),
        migrations.AddField(
            model_name='message',
            name='resources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='suggested_responses_kind',
            field=api.utils.Fields.EnumField(choices=[('free', 'free'), ('offer', 'offer'), ('ready', 'ready'), ('finish', 'finish')], default='free'),
        ),
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='knowledge_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_questions', to='api.knowledgefield'),
        ),
        migrations.AddField(
            model_name='session',
            name='cached_prompt_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='form_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='live_risk_level',
            field=api.utils.Fields.EnumField(choices=[('none', 'none'), ('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], default='none'),
        ),
        migrations.AddField(
            model_name='session',
            name='state',
            field=api.utils.Fields.EnumField(choices=[('general', 'general'), ('check_in', 'check_in'), ('step_active', 'step_active'), ('awaiting_ready', 'awaiting_ready'), ('completed', 'completed'), ('abandoned', 'abandoned')], default='general'),
        ),
        migrations.AddField(
            model_name='sessionstep',
            name='result_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='done_when',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='reference_material',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='result_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_steps', to='api.knowledgefield'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='source',
            field=api.utils.Fields.EnumField(choices=[('onboarding', 'onboarding'), ('question', 'question'), ('ai', 'ai'), ('admin', 'admin'), ('exercise', 'exercise')], default='onboarding'),
        ),
        migrations.AlterField(
            model_name='step',
            name='completion_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('key__isnull', False)), fields=('exercise', 'key'), name='uniq_step_key_per_exercise'),
        ),
        migrations.AddField(
            model_name='evalcase',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eval_cases', to='api.session'),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='prompt_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.promptversion'),
        ),
        migrations.AddField(
            model_name='sessionmetric',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_metrics', to='api.consumer'),
        ),
        migrations.AddField(
            model_name='sessionmetric',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_metrics', to='api.exercise'),
        ),
        migrations.AddField(
            model_name='sessionmetric',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_metrics', to='api.session'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='uniq_prompt_version_key'),
        ),
        migrations.AddIndex(
            model_name='sessionmetric',
            index=models.Index(fields=['consumer', 'key', 'recorded_at'], name='sessionmetric_cons_key_rec_idx'),
        ),
        migrations.RunPython(backfill_wp1, migrations.RunPython.noop),
    ]
