import os

AWS_ACCESS_KEY_ID = os.environ["AWS_ACCESS_KEY_ID"]
AWS_S3_BUCKET_NAME = os.environ["AWS_S3_BUCKET_NAME"]
AWS_SECRET_ACCESS_KEY = os.environ["AWS_SECRET_ACCESS_KEY"]
AWS_CLOUD_FRONT_DOMAIN = os.environ["AWS_CLOUD_FRONT_DOMAIN"]
AWS_CLOUD_FRONT_RESIZER_DOMAIN = os.environ["AWS_CLOUD_FRONT_RESIZER_DOMAIN"]

EMAIL_FROM = os.environ["EMAIL_FROM"]

SENDGRID_API_KEY = os.environ["SENDGRID_API_KEY"]

STRIPE_SECRET_KEY = os.environ["STRIPE_SECRET_KEY"]

BUNDLE_ID_IOS = os.environ["BUNDLE_ID_IOS"]
BUNDLE_ID_ANDROID = os.environ["BUNDLE_ID_ANDROID"]

GOOGLE_API_KEY = os.environ["GOOGLE_API_KEY"]
APPLE_IN_APP_SHARED_SECRET = os.environ["APPLE_IN_APP_SHARED_SECRET"]

SURVEY_CODE = os.environ["SURVEY_CODE"]
SURVEY_WEB_APP_URL = os.environ["SURVEY_WEB_APP_URL"]
SURVEY_MOBILE_APP_URL = os.environ["SURVEY_MOBILE_APP_URL"]
