"""
Django settings for mendreo project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import atexit
import datetime
import os
import ssl

from pathlib import Path
from tempfile import NamedTemporaryFile

from urllib.parse import urlparse


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('GENERAL_SECRET_KEY', 'dev-insecure-secret-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('GENERAL_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('GENERAL_HOST_DOMAIN', '*').split(',') if h.strip()] + ['127.0.0.1', 'localhost']

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'debug_toolbar',
    'social_django',
    'rest_social_auth',
    'api',
    'celery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'mendreo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mendreo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

default_db = {
    'ENGINE': os.environ.get('DATABASE_ENGINE', 'django.db.backends.postgresql'),
    'NAME': os.environ.get('DATABASE_NAME', 'postgres'),
    'USER': os.environ.get('DATABASE_USER', 'postgres'),
    'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
    'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
    'PORT': os.environ.get('DATABASE_PORT', '5432'),
}

default_db["TEST"] = {
    # CI_NODE_INDEX ignored if not available, such as when performing a local build
    # ensures parallel tests use different databases
    'NAME': 'test_mendreo_' + os.getenv('CI_NODE_INDEX', "local")
}

DATABASES = {
    'default': default_db
}

TEST_RUNNER = 'api.test_runner.ProfileTestRunner'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'api.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=int(os.environ.get('ACCESS_TOKEN_LIFETIME', 5))),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(weeks=52),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ),
}

# Celery - controls the background/async tasks used
CELERY_BROKER_URL = os.environ.get('BROKER_URL', 'memory://')
# celery - makes tasks synchronous for tests/local when DEBUG is true.
# On Replit there is no Celery worker/broker, so CELERY_TASK_ALWAYS_EAGER=True
# is set in the environment to run tasks inline in the web process.
CELERY_TASK_ALWAYS_EAGER = (
    DEBUG
    or os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False').lower() in ('true', '1')
)

# django debug toolbar
INTERNAL_IPS = ['127.0.0.1']

ADMINS = [("keith", "keith@mosaic.ie")]
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_HOST_USER = "apikey"
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
SERVER_EMAIL = "notifications@mendreo.com"

# used by XMLTestRunner, name is as expected in github yaml
TEST_OUTPUT_FILE_NAME = "test-results.xml"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('GOOGLE_OAUTH2_KEY', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('GOOGLE_OAUTH2_SECRET', '')

SOCIAL_AUTH_APPLE_TEAM_ID = os.environ.get("APPLE_TEAM_ID", '')
SOCIAL_AUTH_APPLE_CLIENT_ID = os.environ.get("APPLE_CLIENT_ID", '')
SOCIAL_AUTH_APPLE_REDIRECT_URI = os.environ.get("APPLE_REDIRECT_URI", '')
SOCIAL_AUTH_APPLE_KEY_ID = os.environ.get("APPLE_KEY_ID", '')
SOCIAL_AUTH_APPLE_KEY_SECRET = os.environ.get("APPLE_KEY_SECRET", '')

SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get('FACEBOOK_CLIENT_ID', '')
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get('FACEBOOK_CLIENT_SECRET_KEY', '')
SOCIAL_AUTH_USER_FIELDS = ['email', 'username']
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', ]
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id, name, email'}

AUTHENTICATION_BACKENDS = (
    'api.utils.AppleSignIn.AppleOAuth2',
    'api.utils.AppleSignIn.AppleWebOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'api.user.social_pipeline.create_client',  # custom override to create our customer object
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'api.user.social_pipeline.send_details',  # custom override to return auth details
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler", "stream": "ext://sys.stderr"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
    },
}
