# Generated by Django 5.2.4 on 2025-07-12 12:47

import api.utils.Fields
import charidfield.fields
import cuid
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='qstn_', primary_key=True, serialize=False, unique=True)),
                ('type', api.utils.Fields.EnumField(choices=[('text', 'text'), ('date', 'date'), ('number', 'number'), ('boolean', 'boolean')], default='text')),
                ('attribute_key', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('suggested_responses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='qttr_', primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField()),
                ('value', models.TextField()),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.consumer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consumer', 'question'), name='unique_attribute')],
            },
        ),
    ]
