# Generated by Django 5.2.4 on 2025-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_currency_consumer_stripe_customer_id_price_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
