# Generated by Django 5.2.4 on 2025-07-13 11:20

import charidfield.fields
import cuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_consumer_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='attr_', primary_key=True, serialize=False, unique=True),
        ),
    ]
