# Generated by Django 5.2.4 on 2025-08-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_message_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detailed', models.TextField(null=True)),
                ('observations', models.JSONField(null=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.consumer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
