# Generated by Django 5.2.4 on 2025-08-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_agent_model_alter_summary_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='surveyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.BooleanField(default=False),
        ),
    ]
