# Generated by Django 5.2.4 on 2025-08-20 15:19

import api.utils.Fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_summary_counter_emotions_summary_flexible_thinking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='session',
            name='risk_level',
            field=api.utils.Fields.EnumField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high'), ('critical', 'critical')], default='low', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
