# Generated by Django 5.2.4 on 2025-08-21 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_session_rating_session_risk_level_session_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='id',
        ),
        migrations.AddField(
            model_name='session',
            name='rating_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary', serialize=False, to='api.consumer'),
        ),
    ]
