# Generated by Django 5.2.4 on 2025-09-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_summary_counter_emotions_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attribute',
            name='unique_attribute',
        ),
        migrations.AlterField(
            model_name='question',
            name='attribute_key',
            field=models.CharField(max_length=255),
        ),
    ]
