# Generated by Django 5.2.4 on 2025-09-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_exercise_icon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='assets', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='step',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='steps', to='api.tag'),
        ),
    ]
