# Generated by Django 5.2.4 on 2025-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_session_last_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstep',
            name='completion_label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='attribute_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
