# Generated by Django 5.2.4 on 2025-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_attribute_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='completion_label',
            field=models.TextField(null=True),
        ),
    ]
