# Generated by Django 5.2.4 on 2025-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_message_completion_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='completions_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
