# Generated by Django 5.2.4 on 2025-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_exercise_completions_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cached_history',
            field=models.JSONField(null=True),
        ),
    ]
