# Generated by Django 5.2.4 on 2025-10-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_session_cached_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
