# Generated by Django 5.2.4 on 2025-11-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_question_block_on_value_question_blocks_exercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='blocks_exercise',
            new_name='can_complete_exercise',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='block_on_value',
            new_name='complete_on_value',
        ),
    ]
