# Generated by Django 5.2.4 on 2025-11-13 15:30

import api.utils.Fields
import charidfield.fields
import cuid
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_question_complete_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='rol_', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permissions', serialize=False, to='api.role')),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete')], default='view'), blank=True, default=list, size=None)),
                ('sessions', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete')], default='view'), blank=True, default=list, size=None)),
                ('signups', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view')], default='view'), blank=True, default=list, size=None)),
                ('feedback', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create')], default='view'), blank=True, default=list, size=None)),
                ('exercises', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete')], default='view'), blank=True, default=list, size=None)),
                ('assets', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete')], default='view'), blank=True, default=list, size=None)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete')], default='view'), blank=True, default=list, size=None)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view'), ('create', 'create'), ('edit', 'edit'), ('delete', 'delete')], default='view'), blank=True, default=list, size=None)),
                ('pii', django.contrib.postgres.fields.ArrayField(base_field=api.utils.Fields.EnumField(choices=[('view', 'view')], default='view'), blank=True, default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='api.role'),
        ),
    ]
