# Generated by Django 5.2.4 on 2026-01-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_message_exercise_alter_exercise_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='value',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='positive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
