# Generated by Django 5.2.4 on 2026-01-18 14:59

import charidfield.fields
import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_feedback_user_feedback_value_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='stng_', primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(unique=True)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
