"""
Django settings for mendreo project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import datetime
import os
from urllib.parse import unquote, urlparse

from pathlib import Path


def _database_settings() -> dict:
    """Build DB settings from SUPABASE_DEV_DB_URL or individual DATABASE_* vars."""
    url = os.environ.get("SUPABASE_DEV_DB_URL")
    if url:
        parsed = urlparse(url)
        return {
            "ENGINE": os.environ.get("DATABASE_ENGINE", "django.db.backends.postgresql"),
            "NAME": parsed.path.lstrip("/"),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or 5432),
        }
    return {
        "ENGINE": os.environ.get("DATABASE_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.environ.get("DATABASE_NAME", "postgres"),
        "USER": os.environ.get("DATABASE_USER", "postgres"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD", ""),
        "HOST": os.environ.get("DATABASE_HOST", "localhost"),
        "PORT": os.environ.get("DATABASE_PORT", "5432"),
    }


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('GENERAL_SECRET_KEY', 'dev-insecure-secret-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEPLOYMENT_TARGET = os.environ.get('DEPLOYMENT_TARGET', 'local')

DEBUG = os.environ.get('GENERAL_DEBUG', 'False') == 'True'
# debug_toolbar is dev-only and not installed on worker/Vercel images.
if DEPLOYMENT_TARGET == 'vercel' or DEPLOYMENT_TARGET == 'worker' or DEPLOYMENT_TARGET.startswith('worker'):
    DEBUG = False

# Always allow *.railway.app: only a Railway-hosted deployment would ever
# receive a request with that Host header in the first place, so this is
# safe regardless of DEPLOYMENT_TARGET's exact value (which can be wrong/
# unset due to env var typos on the hosting platform -- a DisallowedHost
# here isn't just a fast 400, see the LOGGING config below for why it's
# far worse than that if left unguarded).
_allowed_extra_hosts = [
    '127.0.0.1', 'localhost', 'healthcheck.railway.app', '.railway.app', '.vercel.app',
]
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('GENERAL_HOST_DOMAIN', '*').split(',') if h.strip()] + _allowed_extra_hosts

if DEPLOYMENT_TARGET == 'vercel' or DEPLOYMENT_TARGET == 'worker' or DEPLOYMENT_TARGET.startswith('worker'):
    # Avoid a DB round-trip on health checks and lightweight HTTP handlers.
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'social_django',
    'rest_social_auth',
    'api',
]

if DEBUG:
    INSTALLED_APPS.insert(9, 'debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
if DEBUG:
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
MIDDLEWARE += [
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'mendreo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mendreo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

default_db = {
    **_database_settings(),
    # SUPABASE_DEV_DB_URL points at Supabase's own connection pooler, which
    # can silently drop idle backend connections. If Django holds onto its
    # own long-lived connection (CONN_MAX_AGE > 0) past that point, the next
    # request's query hangs on a half-dead socket for ~30s before finally
    # erroring out (surfaced as HTTP 500s after a long delay on Railway).
    # Since the pooler already does connection reuse for us, let Django open
    # a fresh (pooled) connection per request instead of layering our own
    # long-lived one on top.
    'CONN_MAX_AGE': int(os.environ.get('DATABASE_CONN_MAX_AGE', '0')),
    'CONN_HEALTH_CHECKS': True,
    'OPTIONS': {
        'connect_timeout': int(os.environ.get('DATABASE_CONNECT_TIMEOUT', '10')),
        # Detect a silently-dropped connection via TCP keepalive instead of
        # waiting on OS-default retransmission timeouts (which can be minutes).
        'keepalives': 1,
        'keepalives_idle': 30,
        'keepalives_interval': 10,
        'keepalives_count': 3,
        # Cap any single query so a runaway/blocked query can't hang a
        # Gunicorn worker forever either.
        'options': f"-c statement_timeout={os.environ.get('DATABASE_STATEMENT_TIMEOUT_MS', '20000')}",
    },
}

default_db["TEST"] = {
    # CI_NODE_INDEX ignored if not available, such as when performing a local build
    # ensures parallel tests use different databases
    'NAME': 'test_mendreo_' + os.getenv('CI_NODE_INDEX', "local")
}

DATABASES = {
    'default': default_db
}

TEST_RUNNER = 'api.test_runner.ProfileTestRunner'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'api.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=int(os.environ.get('ACCESS_TOKEN_LIFETIME', 5))),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(weeks=52),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FileUploadParser',
    ),
}

def _normalize_broker_url(url: str) -> str:
    """Upgrade redis:// to rediss:// (TLS) for hosts that require it.

    Upstash (and similar managed Redis providers) require TLS on their
    public endpoint; a plain redis:// URL fails the connection immediately,
    and Celery/kombu will then retry it forever in a tight loop. On a
    CPU-constrained host that retry storm can starve other processes
    (e.g. Gunicorn) sharing the same container of CPU time.
    """
    if url.startswith('redis://') and '.upstash.io' in url:
        return 'rediss://' + url[len('redis://'):]
    return url


# Celery - controls the background/async tasks used
CELERY_BROKER_URL = _normalize_broker_url(os.environ.get('BROKER_URL', 'memory://'))
# celery - makes tasks synchronous for tests/local when DEBUG is true.
# On Replit there is no Celery worker/broker, so CELERY_TASK_ALWAYS_EAGER=True
# is set in the environment to run tasks inline in the web process.
# On Vercel, tasks are dispatched to Redis and handled by the worker service.
CELERY_TASK_ALWAYS_EAGER = (
    DEPLOYMENT_TARGET != 'vercel'
    and (
        DEBUG
        or os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False').lower() in ('true', '1')
    )
)

# Hybrid deployment: Vercel API delegates AI inference to a long-running worker.
AI_WORKER_URL = os.environ.get('AI_WORKER_URL', '')
INTERNAL_API_SECRET = os.environ.get('INTERNAL_API_SECRET', '')
AI_WORKER_TIMEOUT = float(os.environ.get('AI_WORKER_TIMEOUT', '120'))
# Gemini/genai HTTP client timeout in milliseconds. Without this, requests to
# Google's API have no timeout and a slow/unreachable API permanently blocks
# whichever Gunicorn worker is handling the request (seen as HTTP 499s piling
# up on unrelated endpoints once every worker is stuck this way).
GEMINI_HTTP_TIMEOUT_MS = int(os.environ.get('GEMINI_HTTP_TIMEOUT_MS', str(90 * 1000)))
# Fernet key (url-safe base64) used to encrypt AI provider API keys in the DB.
# Required on the Railway worker (and any process that decrypts keys) in production.
# Generate: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
AI_SECRETS_MASTER_KEY = os.environ.get('AI_SECRETS_MASTER_KEY', '')
# When true, POST /messages (and exercise greetings) enqueue Celery and return
# immediately. Default on for Vercel so clients are not blocked on Gemini.
# Local/tests keep sync so CreateTest still sees the agent reply in-process.
_ai_async_default = 'true' if DEPLOYMENT_TARGET == 'vercel' else 'false'
AI_ASYNC_MESSAGES = os.environ.get('AI_ASYNC_MESSAGES', _ai_async_default).lower() in ('true', '1', 'yes')
CRON_SECRET = os.environ.get('CRON_SECRET', '')

# App cache: Redis when BROKER_URL is redis(s), else per-process locmem.
# Used for Setting prompts and published exercise catalogs.
_broker = CELERY_BROKER_URL or ''
if _broker.startswith(('redis://', 'rediss://')) and 'memory://' not in _broker:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _broker,
            'KEY_PREFIX': 'mendreo',
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'mendreo-local',
            'TIMEOUT': 300,
        }
    }

# django debug toolbar
INTERNAL_IPS = ['127.0.0.1']

ADMINS = [("keith", "keith@mosaic.ie")]
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_HOST_USER = "apikey"
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY', '')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
SERVER_EMAIL = "notifications@mendreo.com"

# used by XMLTestRunner, name is as expected in github yaml
TEST_OUTPUT_FILE_NAME = "test-results.xml"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('GOOGLE_OAUTH2_KEY', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('GOOGLE_OAUTH2_SECRET', '')

SOCIAL_AUTH_APPLE_TEAM_ID = os.environ.get("APPLE_TEAM_ID", '')
SOCIAL_AUTH_APPLE_CLIENT_ID = os.environ.get("APPLE_CLIENT_ID", '')
SOCIAL_AUTH_APPLE_REDIRECT_URI = os.environ.get("APPLE_REDIRECT_URI", '')
SOCIAL_AUTH_APPLE_KEY_ID = os.environ.get("APPLE_KEY_ID", '')
SOCIAL_AUTH_APPLE_KEY_SECRET = os.environ.get("APPLE_KEY_SECRET", '')

SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get('FACEBOOK_CLIENT_ID', '')
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get('FACEBOOK_CLIENT_SECRET_KEY', '')
SOCIAL_AUTH_USER_FIELDS = ['email', 'username']
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', ]
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'fields': 'id, name, email'}

AUTHENTICATION_BACKENDS = (
    'api.utils.AppleSignIn.AppleOAuth2',
    'api.utils.AppleSignIn.AppleWebOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'api.user.social_pipeline.create_client',  # custom override to create our customer object
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'api.user.social_pipeline.send_details',  # custom override to return auth details
)

# Django's own default logging config attaches a `mail_admins` handler to
# `django.security.*` (a DIFFERENT logger name from `django.request`, so
# overriding just the latter below does NOT stop this). That handler
# synchronously opens an SMTP connection with no timeout on every security
# exception (DisallowedHost, SuspiciousOperation, etc.) -- e.g. a stray/bot
# request with an unrecognized Host header. If SMTP is slow or unreachable
# (as on Railway, where outbound port 587 may be blocked/throttled), this
# hangs the Gunicorn worker handling that request until gunicorn's own
# --timeout kills it, surfacing as an unrelated-looking HTTP 500 on whatever
# request happened to trigger it. Route both loggers to console only.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler", "stream": "ext://sys.stderr"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "django.security": {"handlers": ["console"], "level": "ERROR", "propagate": False},
    },
}

# Defense in depth: if anything else ever does try to send mail synchronously
# (e.g. mail_admins from a different logger path), don't let it hang a
# request/worker indefinitely.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
