[build]
builder = "DOCKERFILE"
dockerfilePath = "deploy/worker/worker.dockerfile"

[deploy]
startCommand = "./start-all.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
